GET http://localhost:3001/api/notes

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
        "content": "a",
        "important": true
}

###
DELETE http://localhost:3001/api/notes/6333a54d6ceb671585e75ac1