GET http://localhost:3001/api/notes

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
        "content": "Just testing VSCode REST client",
        "important": true
}

###
DELETE http://localhost:3001/api/notes/63325f1117dbddbc284b1b8b